import "../scss/globals.scss";
import "../scss/theme.scss";
import type { Metadata } from "next";

import React from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app", 
};

export default function RootLayout({ children }: {
  children: React.ReactNode
}) {
  return (
    <html
      lang="en"
      className={"dark"}
    >
      <body className={"text-base"}>{children}</body>
    </html>
  );
}
